spring.application.name=strategy

# 数据库连接配置
spring.datasource.url=jdbc:mysql://localhost:3306/pta_strategy?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
spring.datasource.username=
spring.datasource.password=

# MyBatis 配置
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# AWS SQS 配置
project.sqs.queue-name=sinner-task-queue
# 默认关闭自动爬取角色列表
project.crawler.scheduler-enabled=false

# 本地 Redis 配置
spring.data.redis.host=localhost
spring.data.redis.port=6379
# 本地开发通常不需要密码
# spring.data.redis.password=

# 连接池优化
spring.data.redis.lettuce.pool.max-active=8