CREATE TABLE crawl_task (
    id BIGINT NOT NULL AUTO_INCREMENT,
    url VARCHAR(2048) NOT NULL,
    canonical_url VARCHAR(2048) NOT NULL,
    task_type VARCHAR(32) NOT NULL DEFAULT 'ARTICLE',
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    retry_count INT NOT NULL DEFAULT 0,
    max_retries INT NOT NULL DEFAULT 5,
    worker_id VARCHAR(128),
    error_message TEXT,
    next_retry_at DATETIME(6),
    started_at DATETIME(6),
    finished_at DATETIME(6),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_crawl_task_canonical_url (canonical_url(512)),
    KEY idx_crawl_task_status_retry (status, next_retry_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE news_article (
    id BIGINT NOT NULL AUTO_INCREMENT,
    source VARCHAR(64) NOT NULL DEFAULT 'VOA',
    source_article_id VARCHAR(255),
    url VARCHAR(2048) NOT NULL,
    canonical_url VARCHAR(2048) NOT NULL,
    title_en TEXT,
    title_zh TEXT,
    content_en MEDIUMTEXT,
    content_zh MEDIUMTEXT,
    summary_zh TEXT,
    author VARCHAR(512),
    published_at DATETIME(6),
    content_hash CHAR(64),
    language VARCHAR(16) NOT NULL DEFAULT 'en',
    raw_s3_key VARCHAR(1024),
    processing_status VARCHAR(32) NOT NULL DEFAULT 'CRAWLED',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_news_article_url (canonical_url(512)),
    UNIQUE KEY uk_news_article_content_hash (content_hash),
    KEY idx_news_article_published_at (published_at),
    KEY idx_news_article_status (processing_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE article_chunk (
    id BIGINT NOT NULL AUTO_INCREMENT,
    article_id BIGINT NOT NULL,
    chunk_index INT NOT NULL,
    content_en TEXT,
    content_zh TEXT NOT NULL,
    token_count INT,
    content_hash CHAR(64) NOT NULL,
    milvus_vector_id VARCHAR(128),
    embedding_model VARCHAR(255),
    embedding_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_article_chunk_article FOREIGN KEY (article_id) REFERENCES news_article (id),
    UNIQUE KEY uk_article_chunk_position (article_id, chunk_index),
    UNIQUE KEY uk_article_chunk_hash (content_hash),
    KEY idx_article_chunk_embedding_status (embedding_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
